<?php
/*
 本代码由 成都大猿人网络科技有限公司 原创开发
 官方网址：www.dayuanren.cn
 严禁反编译、逆向等任何形式的侵权行为，违者将追究法律责任
*/
namespace Recharge;
use app\common\model\Porder as PorderModel;
class Lab {
	private $mchid;
	private $apikey;
	private $notify;
	private $apiUrl;
	public function __construct($option) {
		if(isset($option['param1']))goto Ya6eWjgx2;
		goto Ya6ldMhx2;
		Ya6eWjgx2:$Ya6FG=$option['param1'];
		goto Ya6x1;
		Ya6ldMhx2:$Ya6FG='';
		Ya6x1:unset($Ya6tIFH);
		$Ya6tIFH=$Ya6FG;
		$this->mchid=$Ya6tIFH;
		if(isset($option['param2']))goto Ya6eWjgx4;
		goto Ya6ldMhx4;
		Ya6eWjgx4:$Ya6FG=$option['param2'];
		goto Ya6x3;
		Ya6ldMhx4:$Ya6FG='';
		Ya6x3:unset($Ya6tIFH);
		$Ya6tIFH=$Ya6FG;
		$this->apikey=$Ya6tIFH;
		if(isset($option['notify']))goto Ya6eWjgx8;
		goto Ya6ldMhx8;
		Ya6eWjgx8:$Ya6FG=$option['notify'];
		goto Ya6x7;
		Ya6ldMhx8:if(isset($option['param3']))goto Ya6eWjgx6;
		goto Ya6ldMhx6;
		Ya6eWjgx6:$Ya6FH=$option['param3'];
		goto Ya6x5;
		Ya6ldMhx6:$Ya6FH='';
		Ya6x5:$Ya6FG=$Ya6FH;
		Ya6x7:unset($Ya6tIFI);
		$Ya6tIFI=$Ya6FG;
		$this->notify=$Ya6tIFI;
		if(isset($option['param4']))goto Ya6eWjgxa;
		goto Ya6ldMhxa;
		Ya6eWjgxa:$Ya6FG=$option['param4'];
		goto Ya6x9;
		Ya6ldMhxa:$Ya6FG='';
		Ya6x9:unset($Ya6tIFH);
		$Ya6tIFH=$Ya6FG;
		$this->apiUrl=$Ya6tIFH;
	}
	public function recharge($out_trade_num,$mobile,$param,$isp='') {
		unset($Ya6tIFG);
		$Ya6tIFG="str_replace";
		$GLOBALS["A__A__"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG="strpos";
		$GLOBALS["A__A_A"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG="str_replace";
		$GLOBALS["A__AA_"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG="md5";
		$GLOBALS["A__AAA"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=1;
		$AAA_A=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=$param['param1'];
		$AAAA_=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=$GLOBALS["A__A__"]('省','',$isp);
		$AAAAA=$Ya6tIFG;
		$Ya6FG=(bool)$GLOBALS["A__A_A"]($param['oparam3'],"自治州");
		$Ya6FH=!$Ya6FG;
		if($Ya6FH)goto Ya6eWjgxd;
		goto Ya6ldMhxd;
		Ya6eWjgxd:$Ya6FG=$GLOBALS["A__A_A"]($param['oparam3'],"自治州")||$GLOBALS["A__A_A"]($param['oparam3'],"地区");
		goto Ya6xc;
		Ya6ldMhxd:Ya6xc:if($Ya6FG)goto Ya6eWjgxe;
		goto Ya6ldMhxe;
		Ya6eWjgxe:unset($Ya6tIFG);
		$Ya6tIFG=$param['oparam3'];
		$A_____=$Ya6tIFG;
		goto Ya6xb;
		Ya6ldMhxe:if(isset($param['oparam3']))goto Ya6eWjgxg;
		goto Ya6ldMhxg;
		Ya6eWjgxg:$Ya6FG=$GLOBALS["A__A__"]('市','',$param['oparam3']) . '市';
		$Ya6FH=$Ya6FG;
		goto Ya6xf;
		Ya6ldMhxg:$Ya6FH='';
		Ya6xf:unset($Ya6tIFI);
		$Ya6tIFI=$Ya6FH;
		$A_____=$Ya6tIFI;
		Ya6xb:$Ya6FG=$this->mchid . $out_trade_num;
		$Ya6FH=$Ya6FG . $mobile;
		$Ya6FI=$Ya6FH . $AAAA_;
		$Ya6FJ=$Ya6FI . $AAA_A;
		$Ya6FK=$Ya6FJ . $AAAAA;
		$Ya6FL=$Ya6FK . $A_____;
		$Ya6FM=$Ya6FL . $this->notify;
		$Ya6FN=$Ya6FM . $this->apikey;
		unset($Ya6tIFO);
		$Ya6tIFO=$Ya6FN;
		$A____A=$Ya6tIFO;
		unset($Ya6tIFG);
		$Ya6tIFG=$GLOBALS["A__AAA"](urldecode($A____A));
		$A___A_=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=array("partner_id"=>$this->mchid,"partner_order_no"=>$out_trade_num,"account"=>$mobile,"amount"=>$AAAA_,"type"=>$AAA_A,"area"=>$AAAAA,"city"=>$A_____,"notify_url"=>$this->notify,"sign"=>$A___A_);
		$A___AA=$Ya6tIFG;
		return $this->http_post($this->apiUrl,$A___AA);
	}
	private function http_post($url,$param) {
		unset($Ya6tIFG);
		$Ya6tIFG="stripos";
		$GLOBALS["A_AA_A"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=curl_init();
		$A_A___=$Ya6tIFG;
		$Ya6FG=$GLOBALS["A_AA_A"]($url,"https://")!==FALSE;
		if($Ya6FG)goto Ya6eWjgxi;
		goto Ya6ldMhxi;
		Ya6eWjgxi:curl_setopt($A_A___,CURLOPT_SSL_VERIFYPEER,FALSE);
		curl_setopt($A_A___,CURLOPT_SSL_VERIFYHOST,false);
		curl_setopt($A_A___,CURLOPT_SSLVERSION,1);
		goto Ya6xh;
		Ya6ldMhxi:Ya6xh:if(is_string($param))goto Ya6eWjgxk;
		goto Ya6ldMhxk;
		Ya6eWjgxk:unset($Ya6tIFG);
		$Ya6tIFG=$param;
		$A_A__A=$Ya6tIFG;
		goto Ya6xj;
		Ya6ldMhxk:unset($Ya6tIFG);
		$Ya6tIFG=http_build_query($param);
		$A_A__A=$Ya6tIFG;
		Ya6xj:curl_setopt($A_A___,CURLOPT_URL,$url);
		curl_setopt($A_A___,CURLOPT_RETURNTRANSFER,1);
		curl_setopt($A_A___,CURLOPT_POST,true);
		curl_setopt($A_A___,CURLOPT_CONNECTTIMEOUT,30);
		curl_setopt($A_A___,CURLOPT_TIMEOUT,90);
		curl_setopt($A_A___,CURLOPT_POSTFIELDS,$A_A__A);
		curl_setopt($A_A___,CURLOPT_HEADER,0);
		unset($Ya6tIFG);
		$Ya6tIFG=curl_exec($A_A___);
		$A_A_A_=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=curl_getinfo($A_A___);
		$A_A_AA=$Ya6tIFG;
		curl_close($A_A___);
		$Ya6FG=intval($A_A_AA["http_code"])==200;
		if($Ya6FG)goto Ya6eWjgxm;
		goto Ya6ldMhxm;
		Ya6eWjgxm:unset($Ya6tIFG);
		$Ya6tIFG=json_decode($A_A_A_,true);
		$A_AA__=$Ya6tIFG;
		$Ya6FG=$A_AA__['code']==1;
		if($Ya6FG)goto Ya6eWjgxo;
		goto Ya6ldMhxo;
		Ya6eWjgxo:return rjson(0,$A_AA__['msg'],$A_AA__);
		goto Ya6xn;
		Ya6ldMhxo:return rjson(1,$A_AA__['msg'],$A_AA__);
		Ya6xn:goto Ya6xl;
		Ya6ldMhxm:$Ya6vPFG='接口访问失败，http错误码' . $A_A_AA["http_code"];
		return rjson(500,$Ya6vPFG);
		Ya6xl:
	}
	private function http_id($url,$cookies) {
		unset($Ya6tIFG);
		$Ya6tIFG="stripos";
		$GLOBALS["AA__A_"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=curl_init();
		$A_AAA_=$Ya6tIFG;
		$Ya6FG=$GLOBALS["AA__A_"]($url,"https://")!==FALSE;
		if($Ya6FG)goto Ya6eWjgxq;
		goto Ya6ldMhxq;
		Ya6eWjgxq:curl_setopt($A_AAA_,CURLOPT_SSL_VERIFYPEER,FALSE);
		curl_setopt($A_AAA_,CURLOPT_SSL_VERIFYHOST,false);
		curl_setopt($A_AAA_,CURLOPT_SSLVERSION,1);
		goto Ya6xp;
		Ya6ldMhxq:Ya6xp:curl_setopt($A_AAA_,CURLOPT_URL,$url);
		curl_setopt($A_AAA_,CURLOPT_RETURNTRANSFER,1);
		curl_setopt($A_AAA_,CURLOPT_CONNECTTIMEOUT,90);
		curl_setopt($A_AAA_,CURLOPT_TIMEOUT,120);
		curl_setopt($A_AAA_,CURLOPT_HEADER,0);
		curl_setopt($A_AAA_,CURLOPT_COOKIE,$cookies);
		unset($Ya6tIFG);
		$Ya6tIFG=curl_exec($A_AAA_);
		$A_AAAA=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=curl_getinfo($A_AAA_);
		$AA____=$Ya6tIFG;
		curl_close($A_AAA_);
		unset($Ya6tIFG);
		$Ya6tIFG=json_decode($A_AAAA,true);
		$AA___A=$Ya6tIFG;
		return $AA___A["data"];
	}
	private function http_cookie($url,$param) {
		unset($Ya6tIFG);
		$Ya6tIFG="stripos";
		$GLOBALS["AAA__A"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG="preg_match";
		$GLOBALS["AAA_A_"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=curl_init();
		$AA__AA=$Ya6tIFG;
		$Ya6FG=$GLOBALS["AAA__A"]($url,"https://")!==FALSE;
		if($Ya6FG)goto Ya6eWjgxs;
		goto Ya6ldMhxs;
		Ya6eWjgxs:curl_setopt($AA__AA,CURLOPT_SSL_VERIFYPEER,FALSE);
		curl_setopt($AA__AA,CURLOPT_SSL_VERIFYHOST,false);
		curl_setopt($AA__AA,CURLOPT_SSLVERSION,1);
		goto Ya6xr;
		Ya6ldMhxs:Ya6xr:unset($Ya6tIFG);
		$Ya6tIFG=$param;
		$AA_A__=$Ya6tIFG;
		curl_setopt($AA__AA,CURLOPT_URL,$url);
		curl_setopt($AA__AA,CURLOPT_RETURNTRANSFER,1);
		curl_setopt($AA__AA,CURLOPT_POST,true);
		curl_setopt($AA__AA,CURLOPT_CONNECTTIMEOUT,90);
		curl_setopt($AA__AA,CURLOPT_TIMEOUT,120);
		curl_setopt($AA__AA,CURLOPT_POSTFIELDS,$AA_A__);
		curl_setopt($AA__AA,CURLOPT_HEADER,1);
		unset($Ya6tIFG);
		$Ya6tIFG=curl_exec($AA__AA);
		$AA_A_A=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=curl_getinfo($AA__AA);
		$AA_AA_=$Ya6tIFG;
		curl_close($AA__AA);
		$GLOBALS["AAA_A_"]('/Cookie:(.*);/iU',$AA_A_A,$AA_AAA);
		unset($Ya6tIFG);
		$Ya6tIFG=$AA_AAA[0];
		$AAA___=$Ya6tIFG;
		$Ya6FG=intval($AA_AA_["http_code"])==200;
		if($Ya6FG)goto Ya6eWjgxu;
		goto Ya6ldMhxu;
		Ya6eWjgxu:return $AAA___;
		goto Ya6xt;
		Ya6ldMhxu:Ya6xt:
	}
	private function http_cd($url,$param,$cookies) {
		unset($Ya6tIFG);
		$Ya6tIFG="stripos";
		$GLOBALS["A______"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=curl_init();
		$AAA_AA=$Ya6tIFG;
		$Ya6FG=$GLOBALS["A______"]($url,"https://")!==FALSE;
		if($Ya6FG)goto Ya6eWjgxw;
		goto Ya6ldMhxw;
		Ya6eWjgxw:curl_setopt($AAA_AA,CURLOPT_SSL_VERIFYPEER,FALSE);
		curl_setopt($AAA_AA,CURLOPT_SSL_VERIFYHOST,false);
		curl_setopt($AAA_AA,CURLOPT_SSLVERSION,1);
		goto Ya6xv;
		Ya6ldMhxw:Ya6xv:if(is_string($param))goto Ya6eWjgxy;
		goto Ya6ldMhxy;
		Ya6eWjgxy:unset($Ya6tIFG);
		$Ya6tIFG=$param;
		$AAAA__=$Ya6tIFG;
		goto Ya6xx;
		Ya6ldMhxy:unset($Ya6tIFG);
		$Ya6tIFG=http_build_query($param);
		$AAAA__=$Ya6tIFG;
		Ya6xx:curl_setopt($AAA_AA,CURLOPT_URL,$url);
		curl_setopt($AAA_AA,CURLOPT_RETURNTRANSFER,1);
		curl_setopt($AAA_AA,CURLOPT_POST,true);
		curl_setopt($AAA_AA,CURLOPT_CONNECTTIMEOUT,90);
		curl_setopt($AAA_AA,CURLOPT_TIMEOUT,120);
		curl_setopt($AAA_AA,CURLOPT_POSTFIELDS,$AAAA__);
		curl_setopt($AAA_AA,CURLOPT_HEADER,0);
		curl_setopt($AAA_AA,CURLOPT_COOKIE,$cookies);
		unset($Ya6tIFG);
		$Ya6tIFG=curl_exec($AAA_AA);
		$AAAA_A=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=curl_getinfo($AAA_AA);
		$AAAAA_=$Ya6tIFG;
		curl_close($AAA_AA);
		$Ya6FG=intval($AAAAA_["http_code"])==200;
		if($Ya6FG)goto Ya6eWjgx11;
		goto Ya6ldMhx11;
		Ya6eWjgx11:unset($Ya6tIFG);
		$Ya6tIFG=json_decode($AAAA_A,true);
		$AAAAAA=$Ya6tIFG;
		$Ya6FG=$AAAAAA['msg']=='操作成功';
		if($Ya6FG)goto Ya6eWjgx13;
		goto Ya6ldMhx13;
		Ya6eWjgx13:return rjson(0,$AAAAAA['msg'],$AAAAAA);
		goto Ya6x12;
		Ya6ldMhx13:return rjson(1,$AAAAAA['msg'],$AAAAAA);
		Ya6x12:goto Ya6xz;
		Ya6ldMhx11:$Ya6vPFG='接口访问失败，http错误码' . $AAAAA_["http_code"];
		return rjson(500,$Ya6vPFG);
		Ya6xz:
	}
	public function check($out_trade_num) {
		unset($Ya6tIFG);
		$Ya6tIFG="md5";
		$GLOBALS["A___A__"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG="str_replace";
		$GLOBALS["A___A_A"]=$Ya6tIFG;
		$Ya6FG=$this->mchid . $out_trade_num;
		$Ya6FH=$Ya6FG . $this->apikey;
		unset($Ya6tIFI);
		$Ya6tIFI=$Ya6FH;
		$A_____A=$Ya6tIFI;
		unset($Ya6tIFG);
		$Ya6tIFG=$GLOBALS["A___A__"](urldecode($A_____A));
		$A____A_=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=["partner_id"=>$this->mchid,"partner_order_no"=>$out_trade_num,'sign'=>$A____A_];
		$A____AA=$Ya6tIFG;
		return $this->http_post($GLOBALS["A___A_A"]('receiveOrder','queryOrder',$this->apiUrl),$A____AA);
	}
	public function selfcheck($param) {
		unset($Ya6tIFG);
		$Ya6tIFG="in_array";
		$GLOBALS["A__A___"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=M('reapi')->where(['id'=>$param['api_cur_id']])->value('param1');
		$A___AA_=$Ya6tIFG;
		$Ya6FG=!$A___AA_;
		if($Ya6FG)goto Ya6eWjgx15;
		goto Ya6ldMhx15;
		Ya6eWjgx15:return ;
		goto Ya6x14;
		Ya6ldMhx15:Ya6x14:unset($Ya6tIFG);
		$Ya6tIFG=$this->check($param['api_order_number']);
		$A___AAA=$Ya6tIFG;
		$Ya6FG=$A___AAA['errno']==0;
		$Ya6FH=(bool)$Ya6FG;
		if($Ya6FH)goto Ya6eWjgx1a;
		goto Ya6ldMhx1a;
		Ya6eWjgx1a:$Ya6FH=$Ya6FG&&isset($A___AAA['data']['data']['status']);
		goto Ya6x19;
		Ya6ldMhx1a:Ya6x19:$Ya6FJ=(bool)$Ya6FH;
		if($Ya6FJ)goto Ya6eWjgx18;
		goto Ya6ldMhx18;
		Ya6eWjgx18:$Ya6FI=$A___AAA['data']['data']['partner_id']==$A___AA_;
		$Ya6FJ=$Ya6FH&&$Ya6FI;
		goto Ya6x17;
		Ya6ldMhx18:Ya6x17:if($Ya6FJ)goto Ya6eWjgx1b;
		goto Ya6ldMhx1b;
		Ya6eWjgx1b:$Ya6FG=$A___AAA['data']['data']['status']==2;
		if($Ya6FG)goto Ya6eWjgx1d;
		goto Ya6ldMhx1d;
		Ya6eWjgx1d:PorderModel::rechargeSusApi('lab',$param['api_order_number'],$A___AAA['data'],'完成充值');
		goto Ya6x1c;
		Ya6ldMhx1d:$Ya6GiWq=$GLOBALS["A__A___"]($A___AAA['data']['data']['status'],[-1,0,1]);
		if($Ya6GiWq)goto Ya6eWjgx1e;
		goto Ya6ldMhx1e;
		Ya6eWjgx1e:$Ya6FG=$A___AAA['data']['data']['charge_amount']!=$A___AAA['data']['data']['amount'];
		$Ya6FI=(bool)$Ya6FG;
		if($Ya6FI)goto Ya6eWjgx1h;
		goto Ya6ldMhx1h;
		Ya6eWjgx1h:$Ya6FH=$A___AAA['data']['data']['charge_amount']>0;
		$Ya6FI=$Ya6FG&&$Ya6FH;
		goto Ya6x1g;
		Ya6ldMhx1h:Ya6x1g:if($Ya6FI)goto Ya6eWjgx1i;
		goto Ya6ldMhx1i;
		Ya6eWjgx1i:PorderModel::rechargeRateApi('lab',$param['api_order_number'],$A___AAA['data'],$A___AAA['data']['data']['charge_amount']);
		goto Ya6x1f;
		Ya6ldMhx1i:Ya6x1f:goto Ya6x1c;
		Ya6ldMhx1e:Ya6x1c:goto Ya6x16;
		Ya6ldMhx1b:Ya6x16:
	}
	public function notify() {
		unset($Ya6tIFG);
		$Ya6tIFG="in_array";
		$GLOBALS["A_A_AAA"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG="explode";
		$GLOBALS["A_AA___"]=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG="str_replace";
		$GLOBALS["A_AA__A"]=$Ya6tIFG;
		if(I('selfcheck'))goto Ya6eWjgx1k;
		goto Ya6ldMhx1k;
		Ya6eWjgx1k:unset($Ya6tIFG);
		$Ya6tIFG=M('porder p')->join('reapi r','r.id=p.api_cur_id')->where(['r.callapi'=>'Lab','p.status'=>3])->order('p.pegging_time asc ,p.create_time asc')->limit(100)->field('p.id,p.mobile,p.api_order_number,p.api_trade_num,p.api_cur_param_id,p.api_cur_id')->select();
		$A__A__A=$Ya6tIFG;
		foreach($A__A__A as $A__A_A_=>$A__A_AA) {
			unset($Ya6tIFG);
			$Ya6tIFG=M('reapi')->where(['id'=>$A__A_AA['api_cur_id']])->find();
			$A__AA__=$Ya6tIFG;
			$Ya6FG=new Lab($A__AA__);
			unset($Ya6tIFH);
			$Ya6tIFH=$Ya6FG;
			$A__AA_A=$Ya6tIFH;
			unset($Ya6tIFG);
			$Ya6tIFG=$A__AA_A->check($A__A_AA['api_order_number']);
			$A__AAA_=$Ya6tIFG;
			M('porder')->where(['id'=>$A__A_AA['id']])->setField(['pegging_time'=>time()]);
			$Ya6FG=$A__AAA_['errno']==0;
			$Ya6FH=(bool)$Ya6FG;
			if($Ya6FH)goto Ya6eWjgx1n;
			goto Ya6ldMhx1n;
			Ya6eWjgx1n:$Ya6FH=$Ya6FG&&isset($A__AAA_['data']['data']['status']);
			goto Ya6x1m;
			Ya6ldMhx1n:Ya6x1m:if($Ya6FH)goto Ya6eWjgx1o;
			goto Ya6ldMhx1o;
			Ya6eWjgx1o:$Ya6FG=$A__AAA_['data']['data']['status']==2;
			if($Ya6FG)goto Ya6eWjgx1q;
			goto Ya6ldMhx1q;
			Ya6eWjgx1q:PorderModel::rechargeSusApi('lab',$A__A_AA['api_order_number'],$A__AAA_['data'],"完成充值");
			goto Ya6x1p;
			Ya6ldMhx1q:$Ya6GiWq=$GLOBALS["A_A_AAA"]($A__AAA_['data']['data']['status'],[-1,0,1]);
			if($Ya6GiWq)goto Ya6eWjgx1r;
			goto Ya6ldMhx1r;
			Ya6eWjgx1r:$Ya6FG=$A__AAA_['data']['data']['charge_amount']!=$A__AAA_['data']['data']['amount'];
			$Ya6FI=(bool)$Ya6FG;
			if($Ya6FI)goto Ya6eWjgx1u;
			goto Ya6ldMhx1u;
			Ya6eWjgx1u:$Ya6FH=$A__AAA_['data']['data']['charge_amount']>0;
			$Ya6FI=$Ya6FG&&$Ya6FH;
			goto Ya6x1t;
			Ya6ldMhx1u:Ya6x1t:if($Ya6FI)goto Ya6eWjgx1v;
			goto Ya6ldMhx1v;
			Ya6eWjgx1v:$Ya6vPvPFG="已充值：" . $A__AAA_['data']['data']['charge_amount'];
			M('porder')->where(['id'=>$A__A_AA['id'],'status'=>['in',[3]]])->setField(['remark'=>$Ya6vPvPFG]);
			$Ya6FG="已充值:" . $A__A_AA['api_order_number'];
			$Ya6FH=$Ya6FG . '-';
			$Ya6FI=$Ya6FH . $A__AAA_['data']['data']['charge_amount'];
			$Ya6FJ=$Ya6FI . '<br/>';
			echo $Ya6FJ;
			goto Ya6x1s;
			Ya6ldMhx1v:Ya6x1s:goto Ya6x1p;
			Ya6ldMhx1r:Ya6x1p:goto Ya6x1l;
			Ya6ldMhx1o:Ya6x1l:
		}
		goto Ya6x1j;
		Ya6ldMhx1k:if(I('remove'))goto Ya6eWjgx1w;
		goto Ya6ldMhx1w;
		Ya6eWjgx1w:unset($Ya6tIFG);
		$Ya6tIFG=M('porder p')->join('reapi r','r.id=p.api_cur_id')->where(['r.callapi'=>'Lab','p.status'=>3,'apply_refund'=>1])->order('p.pegging_time asc ,p.create_time asc')->limit(50)->field('p.id,p.mobile,p.api_order_number,p.api_trade_num,p.api_cur_param_id,p.api_cur_id')->select();
		$A__A__A=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=true;
		$A__AAAA=$Ya6tIFG;
		foreach($A__A__A as $A__A_A_=>$A__A_AA) {
			unset($Ya6tIFG);
			$Ya6tIFG=M('reapi')->where(['id'=>$A__A_AA['api_cur_id']])->find();
			$A__AA__=$Ya6tIFG;
			$Ya6FG=new Lab($A__AA__);
			unset($Ya6tIFH);
			$Ya6tIFH=$Ya6FG;
			$A__AA_A=$Ya6tIFH;
			unset($Ya6tIFG);
			$Ya6tIFG=true;
			$A__AAAA=$Ya6tIFG;
			if($Ya6tIFG)goto Ya6eWjgx1y;
			goto Ya6ldMhx1y;
			Ya6eWjgx1y:unset($Ya6tIFG);
			$Ya6tIFG=$GLOBALS["A_AA___"]("|",$A__AA__['param5']);
			$A_A____=$Ya6tIFG;
			$Ya6vPvPFG=$A_A____[0] . '/partner/user/login.html';
			$Ya6vPvPFH='userName=' . $A_A____[1];
			$Ya6vPvPFI=$Ya6vPvPFH . '&password=';
			$Ya6vPvPFJ=$Ya6vPvPFI . $A_A____[2];
			unset($Ya6tIFK);
			$Ya6tIFK=$GLOBALS["A_AA__A"]('Cookie: ','',$this->http_cookie($Ya6vPvPFG,$Ya6vPvPFJ));
			$A__AAA_=$Ya6tIFK;
			goto Ya6x1x;
			Ya6ldMhx1y:Ya6x1x:unset($Ya6tIFG);
			$Ya6tIFG=false;
			$A__AAAA=$Ya6tIFG;
			$Ya6FG=$A__AAA_!='';
			if($Ya6FG)goto Ya6eWjgx21;
			goto Ya6ldMhx21;
			Ya6eWjgx21:$Ya6vPFG=$A_A____[0] . '/partner/chargeAccount/list.html?page=1&limit=15&partner_order_no=&account=';
			$Ya6vPFH=$Ya6vPFG . $A__A_AA['mobile'];
			$Ya6vPFI=$Ya6vPFH . '&amount=&type=&status=&charge_status=&notify_status=0';
			unset($Ya6tIFJ);
			$Ya6tIFJ=$this->http_id($Ya6vPFI,$A__AAA_);
			$A_A___A=$Ya6tIFJ;
			foreach($A_A___A as $A_A__A_) {
				$Ya6FG=$A_A__A_['partner_order_no']==$A__A_AA['api_order_number'];
				if($Ya6FG)goto Ya6eWjgx23;
				goto Ya6ldMhx23;
				Ya6eWjgx23:$Ya6vPFG=$A_A____[0] . '/partner/chargeAccount/cancel.html';
				$Ya6vPFH='id=' . $A_A__A_['id'];
				unset($Ya6tIFI);
				$Ya6tIFI=$this->http_cd($Ya6vPFG,$Ya6vPFH,$A__AAA_);
				$A_A__AA=$Ya6tIFI;
				print_r($A_A__AA);
				$Ya6FG=$A_A__AA['errno']==0;
				if($Ya6FG)goto Ya6eWjgx25;
				goto Ya6ldMhx25;
				Ya6eWjgx25:$Ya6FG=$A__A_AA['api_order_number'] . '-';
				$Ya6FH=$Ya6FG . $A__A_AA['mobile'];
				$Ya6FI=$Ya6FH . '-撤单成功</br>';
				echo $Ya6FI;
				goto Ya6x24;
				Ya6ldMhx25:$Ya6FG=$A__A_AA['api_order_number'] . '-';
				$Ya6FH=$Ya6FG . $A__A_AA['mobile'];
				$Ya6FI=$Ya6FH . '-撤单失败，请检查账号密码是否正确！</br>';
				echo $Ya6FI;
				Ya6x24:break 1;
				goto Ya6x22;
				Ya6ldMhx23:Ya6x22:
			}
			goto Ya6x2z;
			Ya6ldMhx21:Ya6x2z:
		}
		goto Ya6x1j;
		Ya6ldMhx1w:if(isset($_POST))goto Ya6eWjgx27;
		goto Ya6ldMhx27;
		Ya6eWjgx27:$Ya6FG=$_POST;
		goto Ya6x26;
		Ya6ldMhx27:$Ya6FG='Null';
		Ya6x26:unset($Ya6tIFH);
		$Ya6tIFH=$Ya6FG;
		$A_A_A__=$Ya6tIFH;
		unset($Ya6tIFG);
		$Ya6tIFG=intval($A_A_A__['charge_amount']);
		$A_A_A_A=$Ya6tIFG;
		unset($Ya6tIFG);
		$Ya6tIFG=intval($A_A_A__['status']);
		$A_A_AA_=$Ya6tIFG;
		$Ya6FG=$A_A_AA_==2;
		if($Ya6FG)goto Ya6eWjgx29;
		goto Ya6ldMhx29;
		Ya6eWjgx29:$Ya6FG=intval($A_A_A__['charge_amount'])==intval($A_A_A__['amount']);
		if($Ya6FG)goto Ya6eWjgx2b;
		goto Ya6ldMhx2b;
		Ya6eWjgx2b:PorderModel::rechargeSusApi('lab',$A_A_A__['partner_order_no'],$A_A_A__,"完成充值");
		echo "success";
		goto Ya6x2a;
		Ya6ldMhx2b:$Ya6vPFG="部分充值：" . $A_A_A__['charge_amount'];
		PorderModel::rechargePartApi('lab',$A_A_A__['partner_order_no'],$A_A_A__,$Ya6vPFG,$A_A_A__['charge_amount']);
		Ya6x2a:goto Ya6x28;
		Ya6ldMhx29:$Ya6GiWq=$GLOBALS["A_A_AAA"]($A_A_AA_,[-2,1,-3]);
		if($Ya6GiWq)goto Ya6eWjgx2c;
		goto Ya6ldMhx2c;
		Ya6eWjgx2c:$Ya6FG=$A_A_A_A==0;
		$Ya6FH=(bool)$Ya6FG;
		if($Ya6FH)goto Ya6eWjgx2f;
		goto Ya6ldMhx2f;
		Ya6eWjgx2f:$Ya6FH=$Ya6FG&&isset($A_A_A__['charge_amount']);
		goto Ya6x2e;
		Ya6ldMhx2f:Ya6x2e:if($Ya6FH)goto Ya6eWjgx2g;
		goto Ya6ldMhx2g;
		Ya6eWjgx2g:$Ya6vPFG=$A_A_A__['remarks'] . "|失败状态码：";
		$Ya6vPFH=$Ya6vPFG . $A_A_AA_;
		PorderModel::rechargeFailApi('lab',$A_A_A__['partner_order_no'],$A_A_A__,$Ya6vPFH);
		goto Ya6x2d;
		Ya6ldMhx2g:if(isset($A_A_A__['charge_amount']))goto Ya6eWjgx2h;
		goto Ya6ldMhx2h;
		Ya6eWjgx2h:$Ya6vPFG=$A_A_A__['remarks'] . "|部分充值：";
		$Ya6vPFH=$Ya6vPFG . $A_A_A__['charge_amount'];
		PorderModel::rechargePartApi('lab',$A_A_A__['partner_order_no'],$A_A_A__,$Ya6vPFH,$A_A_A__['charge_amount']);
		goto Ya6x2d;
		Ya6ldMhx2h:Ya6x2d:echo "success";
		goto Ya6x28;
		Ya6ldMhx2c:echo "未知的回调状态";
		Ya6x28:Ya6x1j:
	}
}
?>