<?php
/*
 本代码由 成都大猿人网络科技有限公司 原创开发
 官方网址：www.dayuanren.cn
 严禁反编译、逆向等任何形式的侵权行为，违者将追究法律责任
*/
namespace app\yrapi\controller;
class Open extends \app\common\controller\Base {
	function _base() {
	}
	public function voucher() {
		unset($D92tIED);
		$D92tIED="in_array";
		$GLOBALS["AAA_A"]=$D92tIED;
		unset($D92tIED);
		$D92tIED="rand";
		$GLOBALS["AAAA_"]=$D92tIED;
		unset($D92tIED);
		$D92tIED="date";
		$GLOBALS["AAAAA"]=$D92tIED;
		unset($D92tIED);
		$D92tIED="substr";
		$GLOBALS["A_____"]=$D92tIED;
		unset($D92tIED);
		$D92tIED="implode";
		$GLOBALS["A____A"]=$D92tIED;
		unset($D92tIED);
		$D92tIED="str_split";
		$GLOBALS["A___A_"]=$D92tIED;
		unset($D92tIED);
		$D92tIED=M('voucher_config')->where(array('status'=>1))->select();
		$A_AAA=$D92tIED;
		$D92ED=!$A_AAA;
		if($D92ED)goto D92eWjgx2;
		goto D92ldMhx2;
		D92eWjgx2:echo "未获得凭证";
		exit();
		goto D92x1;
		D92ldMhx2:D92x1:unset($D92tIED);
		$D92tIED=M('porder o')->join('product p','p.id=o.product_id')->where(array('o.id'=>I('id'),'o.type'=>array('in',array_column($A_AAA,'type_id')),'o.status'=>4))->field('o.*,p.voucher_price,p.voucher_name')->find();
		$AA___=$D92tIED;
		$D92ED=!$AA___;
		if($D92ED)goto D92eWjgx4;
		goto D92ldMhx4;
		D92eWjgx4:echo "未获得凭证";
		exit();
		goto D92x3;
		D92ldMhx4:D92x3:unset($D92tIED);
		$D92tIED=1;
		$AA__A['status']=$D92tIED;
		$D92EE=(bool)$GLOBALS["AAA_A"]($AA___['type'],array(1,2));
		if($D92EE)goto D92eWjgx6;
		goto D92ldMhx6;
		D92eWjgx6:unset($D92tIED);
		$D92tIED=ispstrtoint($AA___['isp']);
		unset($D92tIEF);
		$D92tIEF=$D92tIED;
		$AA__A['isp']=$D92tIEF;
		$D92EE=$GLOBALS["AAA_A"]($AA___['type'],array(1,2))&&$D92tIED;
		goto D92x5;
		D92ldMhx6:D92x5:unset($D92tIED);
		$D92tIED=$AA___['type'];
		$AA__A['type_id']=$D92tIED;
		unset($D92tIED);
		$D92tIED=M('voucher_config')->where($AA__A)->find();
		$AA_A_=$D92tIED;
		$D92ED=!$AA_A_;
		if($D92ED)goto D92eWjgx8;
		goto D92ldMhx8;
		D92eWjgx8:echo "订单没有凭证";
		exit();
		goto D92x7;
		D92ldMhx8:D92x7:unset($D92tIED);
		$D92tIED=array();
		$AA_AA=$D92tIED;
		if($AA_A_['is_no'])goto D92eWjgxa;
		goto D92ldMhxa;
		D92eWjgxa:unset($D92tIED);
		$D92tIED=array('type'=>'txt','left'=>$AA_A_['no_left'],'top'=>$AA_A_['no_top'],'size'=>$AA_A_['no_size'],'color'=>$AA_A_['no_color'],'text'=>$AA___['order_number']);
		$AA_AA[]=$D92tIED;
		goto D92x9;
		D92ldMhxa:D92x9:if($AA_A_['is_mobile'])goto D92eWjgxc;
		goto D92ldMhxc;
		D92eWjgxc:unset($D92tIED);
		$D92tIED=array('type'=>'txt','left'=>$AA_A_['mobile_left'],'top'=>$AA_A_['mobile_top'],'size'=>$AA_A_['mobile_size'],'color'=>$AA_A_['mobile_color'],'text'=>$AA___['mobile']);
		$AA_AA[]=$D92tIED;
		goto D92xb;
		D92ldMhxc:D92xb:if($AA_A_['is_date'])goto D92eWjgxe;
		goto D92ldMhxe;
		D92eWjgxe:unset($D92tIED);
		$D92tIED=array('type'=>'txt','left'=>$AA_A_['date_left'],'top'=>$AA_A_['date_top'],'size'=>$AA_A_['date_size'],'color'=>$AA_A_['date_color'],'text'=>time_format($AA___['finish_time']));
		$AA_AA[]=$D92tIED;
		goto D92xd;
		D92ldMhxe:D92xd:if($AA_A_['is_price'])goto D92eWjgxg;
		goto D92ldMhxg;
		D92eWjgxg:if($AA___['voucher_price'])goto D92eWjgxi;
		goto D92ldMhxi;
		D92eWjgxi:$D92vPED=$AA___['voucher_price'];
		goto D92xh;
		D92ldMhxi:$D92vPED=$AA___['total_price'];
		D92xh:unset($D92tIEE);
		$D92tIEE=array('type'=>'txt','left'=>$AA_A_['price_left'],'top'=>$AA_A_['price_top'],'size'=>$AA_A_['price_size'],'color'=>$AA_A_['price_color'],'text'=>$D92vPED);
		$AA_AA[]=$D92tIEE;
		goto D92xf;
		D92ldMhxg:D92xf:if($AA_A_['is_product'])goto D92eWjgxk;
		goto D92ldMhxk;
		D92eWjgxk:if($AA___['voucher_name'])goto D92eWjgxm;
		goto D92ldMhxm;
		D92eWjgxm:$D92vPED=$AA___['voucher_name'];
		goto D92xl;
		D92ldMhxm:$D92vPED=$AA___['product_name'];
		D92xl:unset($D92tIEE);
		$D92tIEE=array('type'=>'txt','left'=>$AA_A_['product_left'],'top'=>$AA_A_['product_top'],'size'=>$AA_A_['product_size'],'color'=>$AA_A_['product_color'],'text'=>$D92vPED);
		$AA_AA[]=$D92tIEE;
		if($AA___['isp'])goto D92eWjgxo;
		goto D92ldMhxo;
		D92eWjgxo:$D92vPED=$AA___['isp'];
		goto D92xn;
		D92ldMhxo:$D92vPED=$AA___['isp'];
		D92xn:unset($D92tIEE);
		$D92tIEE=array('type'=>'txt','left'=>$AA_A_['product_left'],'top'=>$AA_A_['product_top'],'size'=>$AA_A_['product_size'],'color'=>$AA_A_['product_color'],'text'=>$D92vPED);
		$AA_AA[]=$D92tIEE;
		if($AA___['guishu_pro'])goto D92eWjgxq;
		goto D92ldMhxq;
		D92eWjgxq:$D92vPED=$AA___['guishu_pro'];
		goto D92xp;
		D92ldMhxq:$D92vPED=$AA___['guishu_pro'];
		D92xp:unset($D92tIEE);
		$D92tIEE=array('type'=>'txt','left'=>$AA_A_['product_left'],'top'=>$AA_A_['product_top'],'size'=>$AA_A_['product_size'],'color'=>$AA_A_['product_color'],'text'=>$D92vPED);
		$AA_AA[]=$D92tIEE;
		$D92ED=$AA___['charge_kami']=='';
		if($D92ED)goto D92eWjgxs;
		goto D92ldMhxs;
		D92eWjgxs:$D92ED='7426' . $GLOBALS["AAAA_"](1000000000,9999999999);
		$D92EE=$D92ED . $GLOBALS["AAAAA"]('Ymd',strtotime($GLOBALS["AAAAA"]("Y-m-d H:i:s",intval($AA___['finish_time']))));
		$D92EF=$D92EE . $GLOBALS["A_____"]($GLOBALS["A____A"](NULL,array_map('ord',$GLOBALS["A___A_"]($GLOBALS["A_____"](uniqid(),7,13),1))),0,6);
		unset($D92tIEG);
		$D92tIEG=$D92EF;
		$AAA__=$D92tIEG;
		M('porder')->where(['id'=>$AA___['id']])->setField(['charge_kami'=>$AAA__]);
		goto D92xr;
		D92ldMhxs:D92xr:if($AA___['charge_kami'])goto D92eWjgxu;
		goto D92ldMhxu;
		D92eWjgxu:$D92vPED=$AA___['charge_kami'];
		goto D92xt;
		D92ldMhxu:$D92vPED=$AAA__;
		D92xt:unset($D92tIEE);
		$D92tIEE=array('type'=>'txt','left'=>$AA_A_['product_left'],'top'=>$AA_A_['product_top'],'size'=>$AA_A_['product_size'],'color'=>$AA_A_['product_color'],'text'=>$D92vPED);
		$AA_AA[]=$D92tIEE;
		goto D92xj;
		D92ldMhxk:D92xj:$this->assign('txtdata',json_encode($AA_AA));
		$this->assign('bgpath',$AA_A_['path']);
		return view();
	}
}
?>